[colors.primary]
  # Default colors
#	background = '0x1f1f21' # original
#	background = '0x171414' # dark-red
    background = '0x2b2c35' # nordic-grey-altered
	foreground = '0xc0c5ce'

  # Normal colors
[colors.normal]
	black = '0x2b303b'
    red = '0xbf616a'
    green = '0xa3be8c'
    yellow = '0xebcb8b'
    blue = '0x8fa1b3'
    magenta = '0xb48ead'
    cyan = '0x96b5b4'
    white = '0xc0c5ce'

  # Bright colors
[colors.bright]
    black = '0x65737e'
    red = '0xbf616a'
    green = '0xa3be8c'
    yellow = '0xebcb8b'
    blue = '0x8fa1b3'
    magenta = '0xb48ead'
    cyan = '0x96b5b4'
    white = '0xeff1f5'



[cursor.style]
shape = "Block"
blinking = "Never"

[font]
size = 15 

[font.normal]
family = "Terminus"
style = "Regular"
